ADS-517 Update docs for ADS-1.6.0.0
arenadata/docs_ads pull request #7
Opened 2021-02-18 14:25 UTC by denisko890

1) Update info about Monitoring Clients service
2) Added page about Security in ADS
3) Added page about integration with ADPS
4) Update Release notes

2021-02-19 07:27 UTC, inikerin approved these changes

2021-02-19 09:39 UTC, tipsybsd commented on source/Release/index.rst
> +В документе представлены официальные версии продуктов Apache в версии **ADS 1.6.0.0**, описаны новые функциональности компонентов и известные проблемы.
I think "описана новАЯ функциональносТЬ компонентов" will be more correct.

2021-02-19 09:41 UTC, tipsybsd commented on source/Release/index.rst
> -+ Добавлен dashboard в **Grafana** для метрик сервиса *MiNiFi*;
What is "Check" exactly? Action ("действие") or what?

2021-02-19 09:41 UTC, tipsybsd commented on source/Release/index.rst
> ++ Миграция Kafka-Manager в Docker контейнер.
Is that a "new function" ?

2021-02-19 09:59 UTC, denisko890 commented on source/Release/index.rst
> -+ Добавлен dashboard в **Grafana** для метрик сервиса *MiNiFi*;
Да, добавлю уточнение, что это действие

2021-02-19 09:59 UTC, denisko890 commented on source/Release/index.rst
> +В документе представлены официальные версии продуктов Apache в версии **ADS 1.6.0.0**, описаны новые функциональности компонентов и известные проблемы.
Спорно, подумаю

2021-02-19 09:59 UTC, denisko890 commented on source/Release/index.rst
> ++ Миграция Kafka-Manager в Docker контейнер.
Да, согласен. Сделаю ещё раздел

2021-02-19 10:48 UTC, tipsybsd commented on source/Release/index.rst
> +В документе представлены официальные версии продуктов Apache в версии **ADS 1.6.0.0**, описаны новые функциональности компонентов и известные проблемы.
If we define "функциональность" as "набор функций", then "новая функциональность компонентов" looks pretty good, IMHO

2021-02-20 07:37 UTC, denisko890 commented on source/Release/index.rst
> +В документе представлены официальные версии продуктов Apache в версии **ADS 1.6.0.0**, описаны новые функциональности компонентов и известные проблемы.
Done

2021-02-20 07:37 UTC, denisko890 commented on source/Release/index.rst
> -+ Добавлен dashboard в **Grafana** для метрик сервиса *MiNiFi*;
Done

2021-02-20 07:37 UTC, denisko890 commented on source/Release/index.rst
> ++ Миграция Kafka-Manager в Docker контейнер.
Done

2021-02-20 09:31 UTC, lshev requested changes
Check

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Manage_tools_upgrade.rst
> +.. important:: При установленном сервисе *Monitoring Clients*, после обновления бандла необходимо произвести повторный `импорт конфигурационных параметров кластера мониторинга <../Install/create_clus
Запятая не нужна

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Ranger.rst
> +Enterprise версия бандла **ADS** имеет в своём составе Ranger Kafka Plugin. Это позволяет произвести интеграцию ADS и ADPS.
"Enterprise-версия" или "Версия Enterprise"
своём - через "е". Как-то так сложилось, что "ё" не используется в документации, надо придерживаться единообразия.

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Ranger.rst
> +Enterprise версия бандла **ADS** имеет в своём составе Ranger Kafka Plugin. Это позволяет произвести интеграцию ADS и ADPS.
ASD и ADPS - как продукты, выделить **жирным**

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Ranger.rst
> +.. note:: Подробнее об ADPS можно прочитать `здесь <https://docs.arenadata.io/adps/>`_
"здесь" лучше заменить на "по ссылке"

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Ranger.rst
> +.. note:: Плагин не имеет смысла без какой-либо аутентификации. Поэтому заранее включите `SASL/PLAIN <./Security.html>`_ на кластере.
Плагин не имеет смысла без какой-либо аутентификации, поэтому заранее следует включить `SASL/PLAIN <./Security.html>`_ на кластере

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Ranger.rst
> +На странице сервиса *Kafka* кластера ADS в разделе “Run action”, выбрать Manager Ranger Plugin (:numref:`Рис.%s. <manage_ranger_plugin>`).
Запятая не нужна. 
ADS и Manager Ranger Plugin **выделить**

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Ranger.rst
> +Выберите необходимое состояние (Enabled/Disabled) (:numref:`Рис.%s. <manage_ranger_plugin_popup>`).
-> Выбрать

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Ranger.rst
> +После чего запустится процесс активации плагина и создание стандартных политик на стороне Ranger.
В документации настоящее время: 
-> запускается
**Ranger**

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Ranger.rst
> ++ all - topic
двойной дефис дает тире --
В конце спика ;

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Ranger.rst
> +После включения плагина, определение прав к сервису *Kafka* для пользователя определяется в *Ranger*.
Запятая не нужна

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Ranger.rst
> +Подробнее о пользователях для сервисов смотрите `Безопасность в кластере ADS <./Security.html>`_
"смотрите" убрать

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Ranger.rst
> +Подробнее об использовании Ranger смотрите `документацию ADPS <https://docs.arenadata.io/adps/>`_
"смотрите" убрать
**Ranger**

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +Enterprise версия бандла **ADS** предоставляет поддержку SASL/PLAIN аутентификации для сервисов *Kafka*, *KSQL*, *Kafka-Rest*, *Schema-Registry*, *Kafka-Manager*.
Enterprise-версия или Версия Enterprise

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +Данный функционал обеспечивает безопасность кластера Kafka.
**Kafka**

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +После установки *Kafka* и зависимых сервисов с помощью **ADCM**, в кластере появляется возможность включить аутентификацию SASL/PLAIN с помощью кластерной кнопки *Enable PLAIN* (:numref:`Рис.%s. <ena
Запятая не нужна

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +После чего произойдет конфигурация сервисов для SASL/PLAIN. *Enable PLAIN* включает в себя конфигурирование сервисов *Kafka*, *KSQL*, *Kafka-Rest*, *Schema-Registry*, *Kafka-Manager*.
После чего происходит

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +Данные сервисы имеют специальных пользователей, с помощью которых происходит соединение с Kafka кластером.
с Kafka-кластером или с кластером Kafka

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +-----------------------
чтобы синтаксис сработал, надо знаки "----" довести до конца слов заголовка. Так со всеми заголовками, иначе будет сплошной текст в web

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +В всплывающем окне необходимо ввести данные пользователя, а именно username и password (:numref:`Рис.%s. <create_update_user_popup>`).
как поля для ввода, я бы в тескте слова "username" и "password" выделила *курсивом*

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +.. note:: За раз можно создать/обновить только одного пользователя. Создание пользователя происходит только в конфигурации *Kafka*. Для других сервисов необходимо использовать собственные jaas файлы.
jaas-файлы или файлы jaas

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +Для подключения к кластеру *Kafka* с аутентификацией SASL/PLAIN требуется настройка jaas файлов. Jaas файл позволяет производить соединение под конкретным пользователем.
Для подключения к кластеру *Kafka* с аутентификацией SASL/PLAIN требуется настройка jaas-файлов, которые необходимы для соединения под конкретным пользователем.

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +Jaas файл включает в себя следующее содержание для SASL/PLAIN аутентификации:
Jaas-файл

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +*sasl.mechanism* - Механизм SASL, используемый для клиентских подключений.
двойной дефис = тире. Поэтому 
*sasl.mechanism* -- механизм ....

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +Это может быть любой механизм, для которого доступен поставщик безопасности. GSSAPI - это механизм по умолчанию.
GSSAPI -- механизм ....

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +*security.protocol* - Протокол, используемый для связи с брокерами.
*security.protocol* -- протокол, ....

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +*sasl.jaas.config* - Параметры контекста входа в систему с помощью JAAS для соединений SASL.
*sasl.jaas.config* -- параметры ....

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +*username* - Имя пользователя под которым необходимо произвести соединение.
*username* -- имя пользователя, под которым ....

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +*password* - Пароль указанного пользователя.
*password* -- пароль ....

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +.. warning:: Указанные пользователи и пароли сначала должны быть добавлены в кластер *Kafka*. Подробнее смотри `Добавление/Обновление пользователя`_
слово "смотри" убрать

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +Рассмотрим использование jaas файлов для подключения к *Kafka* на примере Schema-Registry.
jaas-файлов

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +Предположим есть потребность записи данных в топик с помощью *kafka-avro-console-producer*. Для этого необходимо произвести вызов с дополнительными параметрами.
в конце :

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +Для вызова *kafka-avro-console-consumer* необходимо произвести аналогичный вызов.
в конце :

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +.. warning:: Если включен *Ranger Kafka Plugin* или *ACL*, то обратите внимание на выданные права и политики для пользователя!
... то важно обратить внимание на ...
Знак ! убрать - и так понятно, что warning

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +Аналогично производятся вызовы для создания различных Consumer и Producer в *Kafka* кластер.
Kafka-кластер или кластер *Kafka*

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> +Следует добавлять следующие параметры при вызове:
При вызове следует добавлять следующие параметры:

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> ++ --consumer.config /some/path/to/jaas/my_jaas_file_to_consume_message.properties - Для вызова Consumer;
-- для вызова  ....

2021-02-20 09:31 UTC, lshev commented on source/AdminGuide/Security.rst
> ++ --producer.config /some/path/to/jaas/my_jaas_file_to_produce_message.properties - Для вызова Producer.
-- для вызова  ....

2021-02-20 09:31 UTC, lshev commented on source/Install/create_cluster/index.rst
> +В новой версии **ADS** появилась поддержка Service Dependency Tree. Данный функционал не позволяет пользователю забыть о зависимых сервисах.
в новой - в какой? может указать:
С версии **ADS** _такой-то_ есть поддержка **Service Dependency Tree**.

2021-02-20 09:31 UTC, lshev commented on source/Install/create_cluster/index.rst
> +Так, для работы сервиса Schema-Registry необходим обязательный сервис Kafka (:numref:`Рис.%s. <dependency_tree>`).
*Schema-Registry* и *Kafka*

2021-02-20 09:31 UTC, lshev commented on source/Release/index.rst
> +В документе представлены официальные версии продуктов Apache в версии **ADS 1.6.0.0**, описаны новая функциональность компонентов и известные проблемы.
как вариант:
... дано описание новой функциональности компонентов и известных проблем.

2021-02-20 09:31 UTC, lshev commented on source/Release/index.rst
> ++ Поддержка Ranger Kafka Plugin;
*Ranger Kafka Plugin*

2021-02-20 09:31 UTC, lshev commented on source/Release/index.rst
> ++ Поддержка Service Dependency Tree;
*Service Dependency Tree*

2021-02-20 09:31 UTC, lshev commented on source/Release/index.rst
> ++ Сервисные действия *Check* также производит проверку сервисов с помощью утилиты systemctl.
-> Сервисное действие
*systemctl*

2021-02-20 09:31 UTC, lshev commented on source/Release/index.rst
> ++ Миграция *Kafka-Manager* в Docker контейнер;
Docker-контейнер или контейнер Docker

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Manage_tools_upgrade.rst
> +.. important:: При установленном сервисе *Monitoring Clients*, после обновления бандла необходимо произвести повторный `импорт конфигурационных параметров кластера мониторинга <../Install/create_clus
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Ranger.rst
> +Enterprise версия бандла **ADS** имеет в своём составе Ranger Kafka Plugin. Это позволяет произвести интеграцию ADS и ADPS.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Ranger.rst
> +Enterprise версия бандла **ADS** имеет в своём составе Ranger Kafka Plugin. Это позволяет произвести интеграцию ADS и ADPS.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Ranger.rst
> +.. note:: Подробнее об ADPS можно прочитать `здесь <https://docs.arenadata.io/adps/>`_
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Ranger.rst
> +На странице сервиса *Kafka* кластера ADS в разделе “Run action”, выбрать Manager Ranger Plugin (:numref:`Рис.%s. <manage_ranger_plugin>`).
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Ranger.rst
> +.. note:: Плагин не имеет смысла без какой-либо аутентификации. Поэтому заранее включите `SASL/PLAIN <./Security.html>`_ на кластере.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Ranger.rst
> +Выберите необходимое состояние (Enabled/Disabled) (:numref:`Рис.%s. <manage_ranger_plugin_popup>`).
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Ranger.rst
> +После чего запустится процесс активации плагина и создание стандартных политик на стороне Ranger.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Ranger.rst
> ++ all - topic
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Ranger.rst
> +После включения плагина, определение прав к сервису *Kafka* для пользователя определяется в *Ranger*.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Ranger.rst
> +Подробнее о пользователях для сервисов смотрите `Безопасность в кластере ADS <./Security.html>`_
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Ranger.rst
> +Подробнее об использовании Ranger смотрите `документацию ADPS <https://docs.arenadata.io/adps/>`_
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +Enterprise версия бандла **ADS** предоставляет поддержку SASL/PLAIN аутентификации для сервисов *Kafka*, *KSQL*, *Kafka-Rest*, *Schema-Registry*, *Kafka-Manager*.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +Данный функционал обеспечивает безопасность кластера Kafka.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +После установки *Kafka* и зависимых сервисов с помощью **ADCM**, в кластере появляется возможность включить аутентификацию SASL/PLAIN с помощью кластерной кнопки *Enable PLAIN* (:numref:`Рис.%s. <ena
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +После чего произойдет конфигурация сервисов для SASL/PLAIN. *Enable PLAIN* включает в себя конфигурирование сервисов *Kafka*, *KSQL*, *Kafka-Rest*, *Schema-Registry*, *Kafka-Manager*.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +Данные сервисы имеют специальных пользователей, с помощью которых происходит соединение с Kafka кластером.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +-----------------------
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +В всплывающем окне необходимо ввести данные пользователя, а именно username и password (:numref:`Рис.%s. <create_update_user_popup>`).
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +.. note:: За раз можно создать/обновить только одного пользователя. Создание пользователя происходит только в конфигурации *Kafka*. Для других сервисов необходимо использовать собственные jaas файлы.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +Для подключения к кластеру *Kafka* с аутентификацией SASL/PLAIN требуется настройка jaas файлов. Jaas файл позволяет производить соединение под конкретным пользователем.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +Jaas файл включает в себя следующее содержание для SASL/PLAIN аутентификации:
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +*sasl.mechanism* - Механизм SASL, используемый для клиентских подключений.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +Это может быть любой механизм, для которого доступен поставщик безопасности. GSSAPI - это механизм по умолчанию.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +*security.protocol* - Протокол, используемый для связи с брокерами.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +*sasl.jaas.config* - Параметры контекста входа в систему с помощью JAAS для соединений SASL.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +*username* - Имя пользователя под которым необходимо произвести соединение.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +*password* - Пароль указанного пользователя.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +.. warning:: Указанные пользователи и пароли сначала должны быть добавлены в кластер *Kafka*. Подробнее смотри `Добавление/Обновление пользователя`_
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +Рассмотрим использование jaas файлов для подключения к *Kafka* на примере Schema-Registry.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +Предположим есть потребность записи данных в топик с помощью *kafka-avro-console-producer*. Для этого необходимо произвести вызов с дополнительными параметрами.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +.. warning:: Если включен *Ranger Kafka Plugin* или *ACL*, то обратите внимание на выданные права и политики для пользователя!
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> +Аналогично производятся вызовы для создания различных Consumer и Producer в *Kafka* кластер.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> ++ --consumer.config /some/path/to/jaas/my_jaas_file_to_consume_message.properties - Для вызова Consumer;
DOne

2021-02-20 11:41 UTC, denisko890 commented on source/AdminGuide/Security.rst
> ++ --producer.config /some/path/to/jaas/my_jaas_file_to_produce_message.properties - Для вызова Producer.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/Install/create_cluster/index.rst
> +В новой версии **ADS** появилась поддержка Service Dependency Tree. Данный функционал не позволяет пользователю забыть о зависимых сервисах.
Done

2021-02-20 11:41 UTC, denisko890 commented on source/Install/create_cluster/index.rst
> +Так, для работы сервиса Schema-Registry необходим обязательный сервис Kafka (:numref:`Рис.%s. <dependency_tree>`).
Done

2021-02-20 11:41 UTC, denisko890 commented on source/Release/index.rst
> ++ Поддержка Ranger Kafka Plugin;
Done

2021-02-20 11:41 UTC, denisko890 commented on source/Release/index.rst
> ++ Поддержка Service Dependency Tree;
Done

2021-02-20 11:41 UTC, denisko890 commented on source/Release/index.rst
> ++ Сервисные действия *Check* также производит проверку сервисов с помощью утилиты systemctl.
DOne

2021-02-20 11:41 UTC, denisko890 commented on source/Release/index.rst
> ++ Миграция *Kafka-Manager* в Docker контейнер;
Done

2021-03-09 07:44 UTC, lshev approved these changes

2021-03-09 07:45 UTC, merged